# Generated by Django 2.2.2 on 2019-07-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
