# Generated by Django 2.2.2 on 2019-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20190701_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='lc_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='lc_name',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
