# Generated by Django 2.2.2 on 2019-07-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0002_auto_20190701_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='auction_photo')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='auction.Auction')),
            ],
        ),
    ]
